### PR TITLE
Create Register page

### PR DESCRIPTION
**Pull request by bhgottfried**
Create a new page for when a user needs to register a new account. Moreover, fix the synchronization issues with the login page where it wasn't getting redirected conditionally based on the server responses.

### CODE REVIEW

**Comment by bhgottfried** [comment]
It looks like this is failing PyTest because there are no tests. I think this is a non-issue since the tests are currently only in Eli's code.

**Comment by EliasTalcott** [comment]
> It looks like this is failing PyTest because there are no tests. I think this is a non-issue since the tests are currently only in Eli's code.

This is accurate. Once some tests exist, this failure will go away.

**Comment by bhgottfried** [comment]
Merging the master branch into this one fixes the linting and database issues so this is ready to go now. Justin's changes also work for me, so I'm happy to squash and merge this once @EliasTalcott and @jhyndma approve/reapprove this.

**Review by jhyndma — APPROVED** [review]
Changes work on my end. Failed Login attempts keep me on the Login page. Looks good. Approved

**Review by EliasTalcott — APPROVED** [review]
The changes to the login page look and behave appropriately for successful and unsuccessful login attempts. I had trouble connecting to the database due to the way we are initializing and creating new instances of mysql, but this issue originated in a different PR. I'll be creating a fix for this issue separately, but the changes here look good to go.

**Pull request merged**
