### PR TITLE
Create utilities to query the Yelp API

### PR DESCRIPTION
**Pull request by EliasTalcott**
This PR will serve to add utilities for querying the Yelp API, including doing business searches, getting individual business details, and getting business reviews. The where/what/how of storing and using this data is out of the scope of this PR and will be addressed once the base functionality is implemented.

### CODE REVIEW

**Review by jhyndma — APPROVED** [review]
Yelp API works. Approved

**Review by bhgottfried — APPROVED** [review]
I'm not sure if this is a WIP still, but in its current state, I think it's fine to merge. We can handle any integration challenges in a separate PR once this, #34, & #35 are merged.

**Review by bhgottfried — APPROVED** [review]
Most recent update refines functionality and adds unit tests. The tests seem complete and all are passing. Re-approved.

**Review by jhyndma — APPROVED** [review]
Added tests pass and the existing functionality has been improved. Re-Approved

**Pull request merged**
