### PR TITLE
Read and store user data in database

### PR DESCRIPTION
**Pull request by EliasTalcott**
This PR adds utilities for reading user profiles from the database and writing data to create new profiles and update existing ones.

### CODE REVIEW

**Review by jhyndma — APPROVED** [review]
Not sure if this PR is done or not. but the changes look good and didn't break anything. Approved until new stuff is added

**Review by bhgottfried — COMMENTED** [review]
Do these changes need to also update the cravr.sql file so that the new tables are initialized when the DB/container is created? If not, then I have no problem approving this.

**Comment by bhgottfried** [comment]
> Do these changes need to also update the cravr.sql file so that the new tables are initialized when the DB/container is created? If not, then I have no problem approving this.

Ah, it looks like you already took care of that in #63. Very nice!

**Review by bhgottfried — APPROVED** [review]
Whoops, I _definitely_ didn't mean to close this... sorry about that. Approved.

**Pull request merged**
